# Generated by Django 6.0.1 on 2026-01-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_notes_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='file_type',
        ),
    ]
